/* import { createSlice, nanoid } from "@reduxjs/toolkit";
import { sub } from "date-fns";

const initialState = [
  {
    id: 1,
    title: "Learning Redux Tool Kit",
    content: "I've heard about this on internet",
    date: sub(new Date(), { minutes: 10 }).toISOString(),
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
      coffee: 0,
    },
  },
  {
    id: 2,
    title: "Slices",
    content: "THe more I say slices, the more I want Pizza",
    date: sub(new Date(), { minutes: 5 }).toISOString(),
    reactions: {
      thumbsUp: 0,
      wow: 0,
      heart: 0,
      rocket: 0,
      coffee: 0,
    },
  },
];

const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
   // postAdded(state, action) {
      //state.push(action.payload); //Immer allows us to write mutating logic in reducers. It doesn't actually mutate the state but it uses the Immer library to detect changes to a "draft state" and produce a brand new immutable state based off those changes.
    //},
    postAdded: {
      reducer(state, action) {
        state.push(action.payload);
      },
      prepare(title, content, userId) {
        return {
          payload: {
            id: nanoid(),
            title,
            content,
            date: new Date().toISOString(), //We can edit the payload object and add the date and log timestamp to it. This way, we don't have to worry about adding the date and timestamp in the component and we can just call the action creator function with title and content.
            userId,
            reactions: {
              thumbsUp: 0,
              wow: 0,
              heart: 0,
              rocket: 0,
              coffee: 0,
            },
          },
        };
      },
    },
    reactionAdded(state, action) {
      const { postId, reaction } = action.payload;
      const existingPost = state.find((post) => post.id === postId);
      if (existingPost) {
        existingPost.reactions[reaction]++;
      }
    },
  },
});

export const selectAllPosts = (state) => state.posts; //This makes sure the we can import posts with worrying about the state structure. We can just import selectAllPosts and use it to get the posts from the state.
//if the state structure changes, we only need to change this selector function and not all the places where we are using the posts.

export const { postAdded, reactionAdded } = postsSlice.actions; //This is automatically generated action creator function for the postAdded reducer function. We can use this to dispatch the action to the store.

export default postsSlice.reducer;
 */

//Redux Async Logic

import { createAsyncThunk, createSlice, nanoid } from "@reduxjs/toolkit";
import { sub } from "date-fns";
import axios from "axios";

const POSTS_URL = "https://jsonplaceholder.typicode.com/posts";

const initialState = {
  posts: [],
  status: "idle", //'idle'|'loading'|'succeeded'|'failed'
  error: null,
};

export const fetchPosts = createAsyncThunk("posts/fetchPosts", async () => {
  try {
    const response = await axios.get(POSTS_URL);
    return [...response.data];
  } catch (error) {
    return error.message;
  }
});

export const addNewPost = createAsyncThunk(
  "posts/addNewPost",
  async (initialPost) => {
    try {
      const response = await axios.post(POSTS_URL, initialPost);
      return response.data;
    } catch (error) {
      return error.message;
    }
  },
);

const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    postAdded: {
      reducer(state, action) {
        state.posts.push(action.payload);
      },
      prepare(title, content, userId) {
        return {
          payload: {
            id: nanoid(),
            title,
            content,
            date: new Date().toISOString(),
            reactions: {
              thumbsUp: 0,
              wow: 0,
              heart: 0,
              rocket: 0,
              coffee: 0,
            },
          },
        };
      },
    },
    reactionAdded(state, action) {
      const { postId, reaction } = action.payload;
      const existingPost = state.posts.find((post) => post.id === postId);
      if (existingPost) {
        existingPost.reactions[reaction]++;
      }
    },
  },
  //Sometimes the slice reducer needs to respond to other action types besides the types it has generated for its own reducers. The extraReducers field lets the slice reducer respond to other action types, in particular the action types generated by createAsyncThunk or in other slices.
  extraReducers(builder) {
    builder
      .addCase(fetchPosts.pending, (state, action) => {
        state.status = "loading";
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = "succeeded";
        let min = 1;
        //adding date and reactions to each of the post that was already fetched using asyncThunk
        //It is given by the action.payload which is the data that was returned from the asyncThunk function. We are mapping through the action.payload and adding date and reactions to each of the post.
        //state here contains the initial state which is an array of posts. We are pushing the new posts to the state.posts array.
        const loadedPosts = action.payload.map((post) => {
          post.date = sub(new Date(), { minutes: min++ }).toISOString();
          post.reactions = {
            thumbsUp: 0,
            wow: 0,
            heart: 0,
            rocket: 0,
            coffee: 0,
          };
          return post;
        });

        // state.posts = state.posts.concat(loadedPosts);//Posts were getting rendered twice because we were concatenating the loadedPosts to the state.posts array which already had the initialState posts. So, we were getting the initialState posts and the loadedPosts from the asyncThunk function. We need to replace the state.posts with the loadedPosts instead of concatenating them.
        state.posts = loadedPosts;
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message;
      })
      .addCase(addNewPost.fulfilled, (state, action) => {
        action.payload.userId = Number(action.payload.userId);
        action.payload.date = new Date().toISOString();
        action.payload.reactions = {
          thumbsUp: 0,
          wow: 0,
          heart: 0,
          rocket: 0,
          coffee: 0,
        };
        console.log(action.payload);
        state.posts.push(action.payload);
      });
  },
});

//Here the state is entire redux store state. We are using the postsSlice reducer to get the posts from the state. The state.posts is the name of the slice reducer that we have defined in the store. The state.posts.posts is the name of the property that we have defined in the initialState of the postsSlice reducer. So, we are returning the posts from the state.
export const selectAllPosts = (state) => state.posts.posts; //state.reducername.stateproperty
export const getPostsStatus = (state) => state.posts.status; //state.reducername.stateproperty
export const getPostsError = (state) => state.posts.error; //state.reducername.stateproperty

export const { postAdded, reactionAdded } = postsSlice.actions;

export default postsSlice.reducer;
